name: Build

on:
  push:
    branches: [dev]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged != 'true') || github.event_name == 'push'
    runs-on: windows-latest
    steps:

    # Replace / with _ in ref name so that it can be used in a filename
    - uses: mad9000/actions-find-and-replace-string@2
      id: sanitizeRef
      with:
        source: ${{ github.ref_name }}
        find: '/'
        replace: '_'
    # Get short-sha so that it can be used in a filename
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha

    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"
    - run: dotnet build -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: QSB-${{ steps.sanitizeRef.outputs.value }}-${{ steps.short-sha.outputs.sha }}
        path: .\QSB\Bin\Release