name: Build

on:
  push:
    branches: [dev]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # only runs if:
    # not a PR, PR is approved, or PR is pushed by the repo owner or a collaborator
    if: github.base_ref == '' || github.event.review.state == 'approved' || github.event.review.author_association == 'COLLABORATOR' || github.event.review.author_association == 'OWNER'
    runs-on: windows-latest
    steps:

    # Replace / with _ in ref name so that it can be used in a filename
    - uses: mad9000/actions-find-and-replace-string@2
      id: sanitizeRef
      with:
        source: ${{ github.ref_name }}
        find: '/'
        replace: '_'
    # Get short-sha so that it can be used in a filename
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha

    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"
    - run: dotnet build -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: QSB-${{ steps.sanitizeRef.outputs.value }}-${{ steps.short-sha.outputs.sha }}
        path: .\QSB\Bin\Release